# Generated by Django 2.1.5 on 2020-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200604_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='user',
        ),
        migrations.AddField(
            model_name='toppings',
            name='pizza',
            field=models.ManyToManyField(related_name='toppings', to='orders.Pizza'),
        ),
    ]
