# Generated by Django 2.1.5 on 2020-06-06 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20200606_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='User',
            field=models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toppings',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Pizza'),
        ),
    ]
