# Generated by Django 2.1.5 on 2020-06-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200606_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order_Sent', 'OS'), ('Order is being made', 'made'), ('your fod is ready', 'ready'), ('on the way', 'OTW'), ('delivered', 'D'), ('cancelled', 'C')], default='Place Order', max_length=100, null=True),
        ),
    ]
