# Generated by Django 2.1.5 on 2020-06-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_toppings_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.CharField(choices=[('small', 'S'), ('large', 'L'), ('regular', 'R')], default='regular', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Regular_Pizza', 'RP'), ('Silicate_Pizza', 'SP'), ('subs', 'SUB'), ('dinner_platters', 'DP'), ('pasta', 'PA')], max_length=64),
        ),
    ]
