# Generated by Django 2.1.5 on 2020-06-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200608_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Regular_Pizza', 'Regular_Pizzas'), ('Silicate_Pizza', 'Silicate_Pizzas'), ('Subs', 'SUB'), ('Dinner_Platter', 'dinner_platters'), ('Pasta', 'pastas')], max_length=64),
        ),
    ]
