# Generated by Django 2.1.5 on 2020-06-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200608_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
