# Generated by Django 2.1.5 on 2020-06-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200609_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('Regular_Pizza', 'Regular_Pizzas'), ('Silicate_Pizza', 'Silicate_Pizzas'), ('Subs', 'SUB'), ('Dinner_Platter', 'dinner_platters'), ('Pasta', 'pastas'), ('salad', 'Salads')], max_length=64),
        ),
    ]
